paths:
 /api/products:
  get:
    summary: obtiene todos los productos guardados en la base
    tags:
     - Products
    responses:
     "200":
     description: los productos se obtienen correctamente
     content:
       application/json:
         schema:
             type: array
             items: 
             $ref: '#components/schemas/Product'
        
  post:
    summary: crea un producto
    tags:
     - Products
    responses:
     "201":
       description: los productos se crean correctamente
      "400":
       description: los datos proporcionados no son suficientes

 /api/products/{pid}:
  get:
    summary: obtiene un productos del id proporcionado
    tags:
     - Products
    parameters:
          name: id
          in: path
          description: Código único del producto.
          required: true
          schema:
            type: string
    responses:
     "200":
      description: los productos se obtienen correctamente
      content:
       application/json:
         schema:
             type: array
             items: 
             $ref: '#components/schemas/Product'
     "500":
          description: "Error interno del servidor"
  delete:
    summary: elimina el producto de la base a partir del id proporcionado
    tags:
     - Products
    parameters:
          name: id
          in: path
          description: Código único del producto.
          required: true
          schema:
            type: string
    responses:
     "200":
     description: el producto se obtiene correctamente
     "400":
     description: error al intentar eliminar el producto
     "500":
          description: "Error interno del servidor"
  put:
    summary: cambia ciertos parametros de un producto a partir del id proporcionado
    tags:
     - Products
    parameters:
          name: id
          in: path
          description: Código único del producto.
          required: true
          schema:
            type: string
    requestBody:
        description: Datos del producto a actualizar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/UpdateProduct'
    responses:
     "200":
     description: el producto se obtiene correctamente
     "400":
     description: error al intentar eliminar el producto
     "500":
          description: "Error interno del servidor"




components:
 schemas:
   Product:
     type: object
     properties:
        title: 
           type: string
           description: Nombre del producto
        description:
           type: string
           description: Descripcion del producto
       price: 
           type: string
           description: Precio del producto
       status: 
           type: boolean
           description: Status
       thumbnail:
           type: image
           description: Fotografia del producto      
      code:
           type: string
           description: Codigo unico de cada producto
      stock: 
           type: string
           description: cantidad de producto dispobles
  requestBodies:
    UpdateProduct:
       type: object
      properties:
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          format: float
          description: Precio del producto
        stock:
          type: number
          description: Stock del producto
        status:
          type: boolean
          description: Estado del producto
        category:
          type: string
          description: Categoría del producto
         thumbnail:
           type: image
           description: Fotografia del producto 
